name: 'Git Commit Security Analyzer'
description: 'Analyzes git commits for potential security issues using AI'
branding:
  icon: 'shield'
  color: 'gray-dark'

inputs:
  model:
    description: 'Ollama model to use'
    required: false
    default: 'qwen2.5-coder:3b'
  start_date:
    description: 'Start date for commit analysis (YYYY-MM-DD)'
    required: false
  end_date:
    description: 'End date for commit analysis (YYYY-MM-DD)'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.model }}
    - ${{ inputs.start_date }}
    - ${{ inputs.end_date }}
